"use client";
import { AccountActions } from "./AccountActions";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "@/components/ui/table";
import { curriculum } from "@/lib/grading";
import type { Role } from "@/lib/access";
type Worker={id:string;name:string;sector:string};
type Assignment={id:string;worker_name:string;worker_id:string;module_id:string;content_version:string;due_at:number;created_at:number;status:string;completed_at:number|null;note:string};
type Data={workers:Worker[];assignments:Assignment[];team:{email:string;role:Role;active:number;user_id:string|null}[];audit:{id:string;actor_email:string;action:string;target:string;at:number;detail:Record<string,unknown>}[];counts:{workers:number;assignments:number;audit:number}};
export type AdminSession={user:{userId:string;email:string;displayName:string};current:{owner:string;name:string;site:string;role:Role}|null;workspaces:{owner:string;role:Role;name:string|null;personal?:boolean}[]};
async function api(body?:unknown):Promise<any>{const r=await fetch('/api/admin/manage',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data:any=await r.json();if(!r.ok)throw new Error(data.error);return data;}
const moduleName=(id:string)=>curriculum.modules.find(m=>m.id===id)?.title[0]??id;
function csvCell(v:unknown){const s=String(v??'');return '"'+(/^[=+@\-\t\r]/.test(s)?"'":"")+s.replaceAll('"','""')+'"';}
export function AdminPanel({view,session,onChange}:{view:'workers'|'assignments'|'team'|'audit'|'settings';session:AdminSession;onChange:()=>Promise<void>}) {
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[status,setStatus]=useState('all');
 const [editing,setEditing]=useState<Worker|null>(null),[workerOpen,setWorkerOpen]=useState(false),[workerName,setWorkerName]=useState(''),[sector,setSector]=useState('Unspecified'),[androidId,setAndroidId]=useState('');
 const [selected,setSelected]=useState<string[]>([]),[moduleId,setModule]=useState('fire'),[due,setDue]=useState(''),[note,setNote]=useState('');
 const [email,setEmail]=useState(''),[role,setRole]=useState<Role>('trainer'),[centre,setCentre]=useState(session.current?.name??''),[site,setSite]=useState(session.current?.site??'');
 const [invitation,setInvitation]=useState('');
 const [assignOpen,setAssignOpen]=useState(false);
 const [cancel,setCancel]=useState<Assignment|null>(null),[reason,setReason]=useState('');
 const writable=session.current?.role!=='viewer';
 async function load(){setData(await api());}
 useEffect(()=>{let active=true;api().then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[session.current?.owner]);
 async function save(body:unknown,done?:()=>void){setBusy(true);setError('');setMessage('');try{const result=await api(body);if(result.invitation)setInvitation(result.invitation);await load();await onChange();setMessage('Changes saved.');done?.();}catch(e){setError(e instanceof Error?e.message:'Could not save.')}finally{setBusy(false)}}
 function worker(w?:Worker){setEditing(w??null);setAndroidId('');setWorkerName(w?.name??'');setSector(w?.sector??'Unspecified');setWorkerOpen(true);}
 const matches=(w:Worker)=>`${w.name} ${w.id} ${w.sector}`.toLowerCase().includes(query.toLowerCase());
 const assignments=data?.assignments.filter(a=>(status==='all'||a.status===status)&&`${a.worker_name} ${a.worker_id} ${moduleName(a.module_id)}`.toLowerCase().includes(query.toLowerCase()))??[];
 function exportReport(){const rows=[['Worker','Worker ID','Training','Due','Status','Completed'],...assignments.map(a=>[a.worker_name,a.worker_id,moduleName(a.module_id),new Date(a.due_at).toISOString(),a.status,a.completed_at?new Date(a.completed_at).toISOString():''])];const url=URL.createObjectURL(new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='training-assignments.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="panel admin-panel">
 {error&&<p className="notice error" role="alert">{error} <Button variant="outline" onClick={()=>{setError('');void load().catch(e=>setError(e.message))}}>Retry</Button></p>}{message&&<p role="status" className="notice success">{message}</p>}
 {!data?<p role="status">Loading workspace…</p>:<>
 {view==='workers'&&<><div className="section-heading"><div><h2>Worker register</h2><p className="muted">Register workers before training, or edit imported profiles.</p></div>{writable&&<Button onClick={()=>worker()}>Add worker</Button>}</div><Input aria-label="Search registered workers" placeholder="Search name, worker ID or sector" value={query} onChange={e=>setQuery(e.target.value)}/><p className="fine">Showing {data.workers.length} of {data.counts.workers} registered workers. Assignments match Android worker IDs. For device training, import the worker’s Android record before assigning.</p><Table><TableHeader><TableRow><TableHead>Worker</TableHead><TableHead>Sector</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{data.workers.filter(matches).map(w=><TableRow key={w.id}><TableCell><strong>{w.name}</strong><span className="table-sub break-all">{w.id}</span></TableCell><TableCell>{w.sector}</TableCell><TableCell>{writable&&<Button variant="outline" onClick={()=>worker(w)}>Edit profile</Button>}</TableCell></TableRow>)}</TableBody></Table>{!data.workers.length&&<p className="empty-message">No workers yet. Add a worker or import an Android training record.</p>}</>}
 {view==='assignments'&&<><h2>Training assignments</h2><div className="assignment-stats">{['assigned','overdue','complete'].map(s=><button key={s} onClick={()=>setStatus(s)} className={`assignment-stat ${s}`}><strong>{data.assignments.filter(a=>a.status===s).length}</strong><span>{s==='assigned'?'Upcoming':s==='overdue'?'Needs follow-up':'Completed'}</span></button>)}</div><p className="fine">Completion requires the latest imported assessment for the assigned curriculum version, begun after assignment, to pass. Practice does not count. These dates are your training plan, not a statutory compliance determination.</p>
 {writable&&<><Button onClick={()=>setAssignOpen(true)}>New assignment</Button><Dialog open={assignOpen} onOpenChange={setAssignOpen}><DialogContent className="max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>Assign training</DialogTitle><DialogDescription>Choose workers, a module and a due date.</DialogDescription></DialogHeader>{error&&<p role="alert" className="notice error">{error}</p>}<form className="admin-form assignment-form" onSubmit={e=>{e.preventDefault();void save({action:'assign',workerIds:selected,moduleId,dueAt:new Date(due).getTime(),note},()=>{setSelected([]);setNote('');setDue('');setAssignOpen(false)})}}><h3>Assign training</h3><div className="form-grid"><label>Module<select value={moduleId} onChange={e=>setModule(e.target.value)}>{curriculum.modules.map(m=><option key={m.id} value={m.id}>{m.title[0]}</option>)}</select></label><label>Due date and time<input type="datetime-local" value={due} required onChange={e=>setDue(e.target.value)}/></label></div><label>Instructions<Input value={note} maxLength={500} onChange={e=>setNote(e.target.value)} placeholder="Optional instructions for the trainer"/></label><Input aria-label="Find workers to assign" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find workers by name or sector"/><div className="assignment-workers">{data.workers.filter(matches).map(w=><label key={w.id}><Checkbox checked={selected.includes(w.id)} onCheckedChange={checked=>setSelected(checked?[...selected,w.id]:selected.filter(id=>id!==w.id))}/><span>{w.name} <small>{w.sector} · {w.id.slice(0,8)}</small></span></label>)}</div><p className="fine">{selected.length} selected · up to 100 per assignment batch</p><Button type="submit" disabled={busy||!due||selected.length===0||selected.length>100}>Assign training</Button></form></DialogContent></Dialog></>}
 <div className="admin-toolbar"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['all','assigned','overdue','complete','cancelled'].map(s=><option key={s}>{s}</option>)}</select></label><Button variant="outline" onClick={exportReport}>Export filtered CSV</Button></div><p className="fine">Showing up to {data.assignments.length} of {data.counts.assignments} assignments.</p><Table><TableHeader><TableRow><TableHead>Worker / module</TableHead><TableHead>Due</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{assignments.map(a=><TableRow key={a.id}><TableCell><strong>{a.worker_name}</strong><span className="table-sub">{moduleName(a.module_id)} · v{a.content_version}</span>{a.note&&<span className="table-sub">{a.note}</span>}</TableCell><TableCell>{new Date(a.due_at).toLocaleString()}</TableCell><TableCell><span className={`badge ${a.status==='complete'?'good':'review'}`}>{a.status}</span></TableCell><TableCell>{writable&&a.status!=='cancelled'&&<Button variant="outline" onClick={()=>{setCancel(a);setReason('')}}>Cancel</Button>}</TableCell></TableRow>)}</TableBody></Table>{!assignments.length&&<p className="empty-message">No assignments match this view.</p>}</>}
 {view==='team'&&<>{invitation&&<div className="notice success"><strong>Invitation code · shown only now</strong><Input aria-label="Invitation code" readOnly value={invitation}/><Button variant="outline" onClick={()=>void navigator.clipboard.writeText(invitation)}>Copy code</Button></div>}<h2>Team access</h2><p className="muted">Admins manage access and settings. Trainers manage learning records and credentials. Viewers can review and export.</p><form className="admin-form" onSubmit={e=>{e.preventDefault();void save({action:'member',email,role,active:true},()=>setEmail(''))}}><div className="form-grid"><label>Staff email<Input type="email" required value={email} maxLength={254} onChange={e=>setEmail(e.target.value)}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="trainer">Trainer</option><option value="viewer">Viewer</option><option value="admin">Admin</option></select></label></div><Button type="submit" disabled={busy}>Save invitation / update role</Button><p className="fine">Share the one-time code privately with your colleague. They must sign in with this email and choose Join a centre. Codes expire after seven days. No email is sent.</p></form><Table><TableHeader><TableRow><TableHead>Staff</TableHead><TableHead>Role</TableHead><TableHead>Access</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{data.team.map(m=><TableRow key={m.email}><TableCell>{m.email}</TableCell><TableCell>{m.role}</TableCell><TableCell>{!m.active?'Revoked':m.user_id?'Accepted':'Invited'}</TableCell><TableCell><Button variant="outline" disabled={busy||m.email.toLowerCase()===session.user.email.toLowerCase()} onClick={()=>void save({action:'member',email:m.email,role:m.role,active:!m.active})}>{m.active?'Revoke access':'Restore access'}</Button></TableCell></TableRow>)}</TableBody></Table></>}
 {view==='audit'&&<><h2>Workspace activity</h2><p className="muted">Recorded changes from the admin release onward. Older actions are not reconstructed.</p><p className="fine">Latest {data.audit.length} of {data.counts.audit} entries.</p><Input aria-label="Filter activity" placeholder="Find actor, action or target" value={query} onChange={e=>setQuery(e.target.value)}/><Table><TableHeader><TableRow><TableHead>When / who</TableHead><TableHead>Action</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{data.audit.filter(r=>`${r.actor_email} ${r.action} ${r.target}`.toLowerCase().includes(query.toLowerCase())).map(r=><TableRow key={r.id}><TableCell>{new Date(r.at).toLocaleString()}<span className="table-sub">{r.actor_email}</span></TableCell><TableCell>{r.action}</TableCell><TableCell className="break-all">{r.target}{Object.keys(r.detail).length>0&&<details><summary>View details</summary><pre className="whitespace-pre-wrap">{JSON.stringify(r.detail,null,2)}</pre></details>}</TableCell></TableRow>)}</TableBody></Table></>}
 {view==='settings'&&<><h2>Training centre settings</h2><form className="admin-form" onSubmit={e=>{e.preventDefault();void save({action:'settings',name:centre,site})}}><label>Centre name<Input value={centre} required minLength={2} maxLength={100} onChange={e=>setCentre(e.target.value)}/></label><label>Site or location<Input value={site} maxLength={150} onChange={e=>setSite(e.target.value)}/></label><Button type="submit" disabled={busy}>Save settings</Button></form><h3>Your account</h3><p>{session.user.displayName}<br/>{session.user.email}</p><AccountActions/></>}
 </>}
 <Dialog open={workerOpen} onOpenChange={setWorkerOpen}><DialogContent><DialogHeader><DialogTitle>{editing?'Edit worker':'Register worker'}</DialogTitle><DialogDescription>Profile changes do not alter saved assessment answers.</DialogDescription></DialogHeader>{error&&<p role="alert" className="notice error">{error}</p>}<form className="admin-form" onSubmit={e=>{e.preventDefault();void save({action:'worker',...(editing?{id:editing.id}:androidId.trim()?{androidId:androidId.trim()}:{}),name:workerName,sector},()=>setWorkerOpen(false))}}><label>Name<Input value={workerName} required maxLength={80} onChange={e=>setWorkerName(e.target.value)}/></label>{!editing&&<label>Android worker ID (optional)<Input value={androidId} maxLength={36} onChange={e=>setAndroidId(e.target.value)} placeholder="Copy the ID from the worker’s Android record"/><span className="fine">Match an existing phone profile to link future imports. Without an ID this is a standalone register entry; import Android records before assigning device training.</span></label>}<label>Sector<select value={sector} onChange={e=>setSector(e.target.value)}>{['Unspecified','Mining','Steel','Mica','Other'].map(s=><option key={s}>{s}</option>)}</select></label><Button type="submit" disabled={busy}>Save worker</Button></form></DialogContent></Dialog>
 <Dialog open={!!cancel} onOpenChange={open=>{if(!open)setCancel(null)}}><DialogContent><DialogHeader><DialogTitle>Cancel this assignment?</DialogTitle><DialogDescription>The assignment and its audit history remain stored.</DialogDescription></DialogHeader>{error&&<p role="alert" className="notice error">{error}</p>}<form className="admin-form" onSubmit={e=>{e.preventDefault();void save({action:'cancel',id:cancel!.id,reason},()=>setCancel(null))}}><label>Reason<Input value={reason} required minLength={5} maxLength={500} onChange={e=>setReason(e.target.value)}/></label><Button type="submit" variant="destructive" disabled={busy}>Cancel assignment</Button></form></DialogContent></Dialog>
 </section>;
}
