'use client';
import {ReviewEvidence} from './ReviewEvidence';
import {Reauthenticate} from './SecuritySettings';
import {useCallback,useEffect,useRef,useState} from 'react';
import {requestJson} from '@/lib/client-api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type{AdminSession}from './AdminPanel';
type Item={id:string;attempt_id:string;worker_name:string;module_id:string;score:number;expires_at:number;requested_by:string;request_note:string;status:string;review_reason:string|null;credential_id:string|null};
export function CertificationQueue({session,refreshVersion,onChange,onReview}:{session:AdminSession;refreshVersion:number;onChange:()=>Promise<void>;onReview:(id:string)=>void}){
 const [rows,setRows]=useState<Item[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[message,setMessage]=useState(''),[filter,setFilter]=useState('pending');const pending=useRef(false);
 const load=useCallback(async()=>{const d=await requestJson<{requests:Item[]}>('/api/credentials');setRows(d.requests);setLoaded(true);setError('')},[]);
 useEffect(()=>{void Promise.resolve().then(load).catch(e=>{setRows([]);setError(e.message)})},[load,refreshVersion]);
 async function decide(id:string,form:FormData){if(pending.current)return;pending.current=true;setBusy(true);setError('');setMessage('');try{await requestJson('/api/credentials','POST',{action:form.get('action'),requestId:id,reason:form.get('reason'),...(form.get('action')==='approve'?{rubric:{evidenceReviewed:form.get('evidenceReviewed')==='on',scopeConfirmed:form.get('scopeConfirmed')==='on',latestAssessment:form.get('latestAssessment')==='on',identityBasis:form.get('identityBasis'),practical:'not-assessed'}}:{})});await load();await onChange();setMessage(form.get('action')==='approve'?'Pilot credential approved and issued.':'Decision saved. The learner can see the reason in their timeline.')}catch(e){setError(e instanceof Error?e.message:'Review failed')}finally{pending.current=false;setBusy(false)}}
 return <section className="panel p-6 mb-6"><h2>Certification review queue</h2><p>Trainer request → independent certifier review → signed pilot credential. Review the assessment answers before deciding. Practical competence and identity are not established by imported app events.</p>
 {message&&<p role="status" className="notice success">{message}</p>}
 {error&&<p className="notice error" role="alert">{error}<Button variant="outline" onClick={()=>void Promise.resolve().then(load).catch(e=>setError(e.message))}>Retry</Button></p>}
 {!loaded&&!error&&<p role="status">Loading review queue…</p>}{loaded&&!rows.length&&<p>No certification requests. Complete and sync all course stages, then submit the latest passed assessment from its review screen.</p>}
 <label>Queue status<select value={filter} onChange={e=>setFilter(e.target.value)}>{['pending','needs-information','approved','rejected','all'].map(s=><option key={s} value={s}>{s.replaceAll('-',' ')}</option>)}</select></label>
 {session.current&&<Reauthenticate email={session.user.email} owner={session.current.owner}/>}
 {rows.filter(r=>filter==='all'||r.status===filter).map(r=><article className="rounded-xl border p-4 my-4" key={r.id}><h3>{r.worker_name} · {r.module_id}</h3><p>{r.score}% · <strong>{r.status}</strong> · Requested validity ends {new Date(r.expires_at).toLocaleString()}</p><p>Evidence note: {r.request_note}</p>{r.review_reason&&<p>Decision: {r.review_reason}</p>}<Button variant="outline" onClick={()=>onReview(r.attempt_id)}>Review assessment answers</Button><ReviewEvidence key={r.id+refreshVersion+r.status} requestId={r.id}/>
 {r.status==='pending'&&session.current?.role==='certifier'&&r.requested_by!==session.user.userId&&<form className="admin-form" onSubmit={e=>{e.preventDefault();void decide(r.id,new FormData(e.currentTarget))}}><label>Review decision<select name="action"><option value="needs-information">Request more information</option><option value="reject">Reject assessment evidence</option><option value="approve">Approve and issue pilot credential</option></select></label><fieldset><legend>Approval checklist — required when approving</legend>{[["evidenceReviewed","I reviewed the assessment answers and available evidence"],["scopeConfirmed","I confirm this is a pilot simulation credential"],["latestAssessment","I checked the current assessment and unresolved errors"]].map(([id,label])=><label className="remember-choice" key={id}><input type="checkbox" name={id}/>{label}</label>)}<label>Identity evidence<select name="identityBasis"><option value="not-verified">Not independently verified</option><option value="centre-roster">Centre roster checked</option><option value="in-person">Checked in person</option></select></label></fieldset><label>Evidence reviewed / decision reason<Input name="reason" minLength={10} maxLength={500} required/></label><p className="fine">Approval rechecks current centre access, your role and the latest assessment. A recent sign-in is required. Use “more information” for correctable omissions. Rejection requires a new eligible assessment. Instructor observations are reviewed separately in Learners & observations.</p><Button disabled={busy}>Confirm review decision</Button></form>}
 {r.status==='needs-information'&&r.requested_by===session.user.userId&&['admin','trainer'].includes(session.current?.role??'')&&<form className="admin-form" onSubmit={e=>{e.preventDefault();void decide(r.id,new FormData(e.currentTarget))}}><input type="hidden" name="action" value="clarify"/><label>Requested information<Input name="reason" minLength={10} maxLength={500} required/></label><Button disabled={busy}>Resubmit for review</Button></form>}
 {r.status==='pending'&&r.requested_by===session.user.userId&&<p className="fine">Waiting for a different authorized certifier. You cannot approve your own request.</p>}
 </article>)}
 </section>
}
