'use client';
import {LocalQr} from './LocalQr';
import {useEffect,useState} from 'react';
import {requestJson} from '@/lib/client-api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import type {AdminSession} from './AdminPanel';
type Data={links:{worker_id:string;name:string;email:string;linked_at:number|null}[];procedures:{id:string;name:string;payload:{module:string;guided:boolean;finished:boolean;criticalFailures:string[];events:{type:string;step:string;action?:string;correct?:boolean;presentation?:string}[]}}[];observations:{id:string;worker_id:string;module_id:string;outcome:string;note:string}[]};
export function InstructorPanel({session,refreshVersion}:{session:AdminSession;refreshVersion:number}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[invitation,setInvitation]=useState(''),[workers,setWorkers]=useState<{id:string;name:string}[]>([]);
 const writable=['admin','trainer'].includes(session.current?.role??'');
 async function load(){const [d,w]=await Promise.all([requestJson<Data>('/api/learners'),requestJson<{workers:{id:string;name:string}[]}>('/api/admin/manage')]);setData(d);setWorkers(w.workers)}
 useEffect(()=>{void Promise.resolve().then(load).catch(e=>setError(e.message))},[refreshVersion]);
 async function save(body:unknown){if(busy)return;setBusy(true);setError('');setInvitation('');try{const d=await requestJson<{url?:string}>('/api/learners','POST',body);if(d.url)setInvitation(d.url);await load()}catch(e){setError(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}
 const roster=<label>Learner<select name="workerId" required defaultValue=""><option value="" disabled>Choose registered learner</option>{workers.map(w=><option key={w.id} value={w.id}>{w.name} · {w.id.slice(0,8)}</option>)}</select></label>;
 return <section className="panel p-6"><h2>Learner enrolment & instructor review</h2><p>Register the learner using the ID shown on their Android phone. Invitations link that profile to an account; they grant no staff access.</p>{error&&<p role="alert" className="notice error">{error}<Button onClick={()=>void Promise.resolve().then(load).catch(e=>setError(e.message))}>Retry</Button></p>}
 {!data&&!error&&<p role="status">Loading learner records…</p>}{writable&&<form className="admin-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({action:'invite',workerId:f.get('workerId'),email:f.get('email')})}}>{roster}<label>Learner account email<Input name="email" type="email" required maxLength={254}/></label><Button disabled={busy}>Create private enrolment link</Button></form>}
 {invitation&&<div role="status" className="notice success"><p>Copy this private link to the intended learner. No email was sent. It expires in seven days.</p><LocalQr value={invitation} label="Private learner enrolment QR"/><Input aria-label="Private enrolment link" readOnly value={invitation} onFocus={e=>e.target.select()}/></div>}
 {data?.links.map(l=><p key={l.worker_id}>{l.name} · {l.email} · {l.linked_at?'Linked':'Invitation pending'} {writable&&<Button variant="outline" disabled={busy} onClick={()=>{if(confirm('Unlink this learner account? Saved training evidence is retained.'))void save({action:'unlink',workerId:l.worker_id})}}>Unlink account</Button>}</p>)}
 <h3>Observed practical assessment</h3><p>Record only an observation you actually conducted under the approved site procedure. This record is separate from the simulation credential and retains your instructor identity.</p>
 {writable&&<form className="admin-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({action:'observe',workerId:f.get('workerId'),moduleId:f.get('moduleId'),observedAt:new Date(String(f.get('observedAt'))).getTime(),outcome:f.get('outcome'),note:f.get('note'),rubric:{identityChecked:f.get('identityChecked')==='on',procedureReviewed:f.get('procedureReviewed')==='on',safeDecisions:f.get('safeDecisions')==='on',sequence:f.get('sequence')==='on',communication:f.get('communication')==='on'}})}}>{roster}<label>Module<select name="moduleId">{['fire','gas','machinery','ppe','emergency'].map(m=><option key={m}>{m}</option>)}</select></label><label>Observed at<Input type="datetime-local" name="observedAt" required/></label>{[['identityChecked','Learner identity checked'],['procedureReviewed','Approved procedure reviewed'],['safeDecisions','Safe decisions demonstrated'],['sequence','Required sequence demonstrated'],['communication','Communication demonstrated']].map(([id,label])=><label className="remember-choice" key={id}><input name={id} type="checkbox" required={id==='identityChecked'||id==='procedureReviewed'}/>{label}</label>)}<label>Outcome<select name="outcome"><option value="needs-practice">More practice needed</option><option value="demonstrated">Criteria demonstrated</option></select></label><label>Observation, procedure reference and limitations<textarea name="note" required minLength={20} maxLength={1000}/></label><Button disabled={busy}>Record observation</Button></form>}
 {data?.observations.map(o=><p key={o.id}>{o.module_id} · {o.outcome} · {o.note}<br/><small>Reference: {o.id}</small></p>)}
 <h3>Scenario decision timelines</h3><p>Latest 200 synced attempts. These are device-reported actions, not hardware-attested skill.</p>{data?.procedures.map(p=><details className="review-card" key={p.id}><summary>{p.name} · {p.payload.module} · {p.payload.guided?'Coached':'Independent'} · {p.payload.finished?'Ended':'In progress'} · {p.payload.criticalFailures.length} critical errors</summary><ol>{p.payload.events.filter(e=>e.type==='action').map((e,i)=><li key={i}>{e.step}: {e.action} · {e.correct?'Accepted':'Needs review'} · {e.presentation}</li>)}</ol></details>)}{data&&!data.procedures.length&&<p>No scenario evidence yet. Learners can sync from their Android training centre screen.</p>}</section>
}
