'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {requestJson} from '@/lib/client-api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {signOut,AccountActions} from './AccountActions';
type Course={id:string;title:string;attemptId:string|null;steps:{id:string;label:string;done:boolean}[]};
type Portal={links:{worker_id:string;name:string;centre:string}[];learner?:string;centre?:string;courses?:Course[];requests?:{id:string;attempt_id:string;module_id:string;status:string;review_reason:string|null;request_note:string;requested_at:number}[];credentials?:{id:string;moduleId:string;status:string;expiresAt:number|null}[];events?:{id:string;request_id:string;action:string;note:string;at:number}[];assignments?:{id:string;module_id:string;due_at:number;note:string}[]};
export function LearnerPortal(){
 const [data,setData]=useState<Portal|null>(null),[worker,setWorker]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[invite,setInvite]=useState('');
 const load=useCallback(async()=>{const d=await requestJson<Portal>('/api/learner'+(worker?'?workerId='+encodeURIComponent(worker):''));setData(d);if(!worker&&d.links.length===1)setWorker(d.links[0].worker_id)},[worker]);
 useEffect(()=>{let live=true;void Promise.resolve().then(()=>{const code=new URLSearchParams(location.hash.slice(1)).get('invite');if(code)setInvite(code);return load()}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[load]);
 async function send(body:unknown){if(busy)return;setBusy(true);setError('');setMessage('');try{await requestJson('/api/learner','POST',body);await load();setMessage('Saved. Your current status is shown below.');setInvite('');if(location.hash.startsWith('#invite='))history.replaceState(null,'','/learn')}catch(e){setError(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}}
 return <main className="learner-page"><header className="learner-header"><div><span className="eyebrow">SURAKSHAAR · LEARNER</span><h1>Your learning journey</h1><p>{data?.centre??'Offline practice. Connected records when you need them.'}</p></div><nav aria-label="Account"><Link href="/">Staff workspace</Link><Button variant="outline" onClick={()=>void signOut().catch(e=>setError(e.message))}>Sign out</Button></nav></header>
 {error&&<p role="alert" className="notice error">{error} <Button onClick={()=>void load().catch(e=>setError(e.message))}>Retry</Button></p>}{message&&<p role="status" className="notice success">{message}</p>}
 {!data&&!error&&<p role="status">Loading your learning record…</p>}
 <details className="panel p-6" open={!data?.links.length||!!invite}><summary>{data?.links.length?"Join another training centre":"Join your training centre"}</summary><p>Your trainer invites your specific learner ID. Joining preserves its identity; it does not merge other learners on a shared phone.</p><form className="admin-form" onSubmit={e=>{e.preventDefault();void send({action:'join',invitation:invite})}}><label>Private learner invitation<Input value={invite} onChange={e=>setInvite(e.target.value)} required maxLength={200} autoComplete="off"/></label><Button disabled={busy}>Confirm enrolment</Button></form></details>
 {!!data?.links.length&&<label className="learner-select">Learner record<select value={worker} onChange={e=>setWorker(e.target.value)}><option value="">Choose a learner</option>{data.links.map(l=><option key={l.worker_id} value={l.worker_id}>{l.name} · {l.centre}</option>)}</select></label>}
 {data?.courses&&<><section><h2>{data.learner} · Course map</h2><p>Learn → guided rehearsal → independent check → knowledge assessment → independent certification review. Steps update after Android sync. A simulation credential does not establish practical competence.</p><div className="journey-grid">{data.courses.map(c=><article className="panel p-6" key={c.id}><h3>{c.title}</h3><ol className="journey-steps">{c.steps.map(s=><li key={s.id} data-complete={s.done}><span aria-hidden>{s.done?'✓':'○'}</span> {s.label}<small>{s.done?'Recorded':'Still to do'}</small></li>)}</ol><p>Next: {c.steps.find(s=>!s.done)?.label??(data.requests?.find(r=>r.attempt_id===c.attemptId)?'Follow your certification timeline below':'Review your evidence and request certification')}</p>{c.steps.every(s=>s.done)&&!data.requests?.some(r=>r.attempt_id===c.attemptId)&&<form className="admin-form" onSubmit={e=>{e.preventDefault();void send({action:'request',workerId:worker,attemptId:c.attemptId,note:new FormData(e.currentTarget).get('note')})}}><label>Evidence / support note<Input name="note" minLength={10} maxLength={500} required placeholder="What should your certifier review?"/></label><p className="fine">Request a pilot simulation credential after completing the course. The reviewer sees learning and practical evidence separately. Requested validity: 180 days.</p><Button disabled={busy}>Submit for independent review</Button></form>}</article>)}</div></section>
 <section className="panel p-6"><h2>Assignments</h2>{!data.assignments?.length?<p>No assigned deadlines. Continue learning at your own pace.</p>:data.assignments.map(a=><p key={a.id}><strong>{a.module_id}</strong> · Due {new Date(a.due_at).toLocaleDateString()} · {a.note}</p>)}</section>
 <section className="panel p-6"><h2>Certification timeline</h2>{!data.requests?.length&&<p>No request yet. Complete and sync the four course stages from Android to get started.</p>}{data.requests?.map(r=><article className="review-card" key={r.id}><h3>{data.courses?.find(c=>c.id===r.module_id)?.title??r.module_id} · {r.status.replaceAll('-',' ')}</h3><p>Submitted {new Date(r.requested_at).toLocaleString()}</p><p>{r.request_note}</p>{r.review_reason&&<p>Reviewer: {r.review_reason}</p>}<ol>{data.events?.filter(e=>e.request_id===r.id).map(e=><li key={e.id}>{new Date(e.at).toLocaleString()} · {e.action}: {e.note}</li>)}</ol>{r.status==='needs-information'&&<form className="admin-form" onSubmit={e=>{e.preventDefault();void send({action:'clarify',workerId:worker,requestId:r.id,note:new FormData(e.currentTarget).get('note')})}}><label>Provide the requested information<Input name="note" minLength={10} maxLength={500} required/></label><Button disabled={busy}>Resubmit for review</Button></form>}{r.status==='rejected'&&<p>Review the reason with your trainer and complete a new eligible assessment.</p>}</article>)}</section>
 <section className="panel p-6"><h2>Credential wallet</h2>{!data.credentials?.length&&<p>Approved credentials will appear here and download during Android sync.</p>}{data.credentials?.map(c=><article className="review-card" key={c.id}><h3>{c.moduleId} · {c.status}</h3><p>{c.expiresAt?'Validity ends '+new Date(c.expiresAt).toLocaleDateString():'No expiry recorded'}</p><a href={'/certificate/'+c.id}>Open certificate / save PDF</a></article>)}</section></>}
 <details className="panel p-6"><summary>Account security</summary><AccountActions/></details><p className="fine">Local pilot · records stay on this training server. Local hosting is reachable only while the host is running.</p></main>
}
