"use client";
import { useState } from "react";
import { ShieldCheck, ArrowRight, Eye, EyeOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export default function Login() {
 const [signup,setSignup]=useState(false),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>) {
  e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');
  try {const response=await fetch(`/api/auth/${signup?'sign-up':'sign-in'}/email`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.get('email'),password:form.get('password'),...(signup?{name:form.get('name')}:{rememberMe:true})})});
   const data:any=await response.json();if(!response.ok)throw new Error(data.message??'Could not sign in. Try again.');window.location.assign('/');
  } catch(e){setError(e instanceof Error?e.message:'Could not connect. Try again.');setBusy(false);}
 }
 return <main className="account-page"><div className="account-brand"><span className="brand-mark"><ShieldCheck size={26}/></span><span>Suraksha Saathi<small>TRAINING CENTRE</small></span></div><section className="account-card"><div className="account-intro"><span className="eyebrow">YOUR WORKSPACE</span><h1>{signup?'Create your account':'Welcome back'}</h1><p>{signup?'Set up your own training centre or join your team with an invitation code.':'Sign in to manage your team’s training.'}</p></div><form className="account-form" onSubmit={submit}>{signup&&<label>Full name<Input name="name" autoComplete="name" required maxLength={80} placeholder="Your name"/></label>}<label>Email address<Input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@organisation.in"/></label><label>Password<div className="password-input"><Input name="password" type={visible?'text':'password'} autoComplete={signup?'new-password':'current-password'} required minLength={signup?12:1} maxLength={128} placeholder={signup?'At least 12 characters':'Enter your password'}/><Button type="button" variant="ghost" size="icon" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</Button></div></label>{error&&<p className="notice error" role="alert">{error}</p>}<Button className="account-submit" type="submit" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}{!busy&&<ArrowRight size={18}/>}</Button></form><div className="account-switch"><span>{signup?'Already have an account?':'New to Suraksha Saathi?'}</span><Button variant="link" disabled={busy} onClick={()=>{setSignup(!signup);setError('')}}>{signup?'Sign in':'Create an account'}</Button></div></section><p className="account-offline">Use the Android app for offline lessons and AR practice.<br/>Your training centre account requires a connection.</p></main>;
}
