'use client';
import {LocalQr} from './LocalQr';
import {useState} from 'react';
import {requestJson} from '@/lib/client-api';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {PasswordInput} from './PasswordInput';
export function SecuritySettings(){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[setup,setSetup]=useState<{totpURI:string;backupCodes:string[]}|null>(null);
 const [sessions,setSessions]=useState<{token:string;userAgent?:string;createdAt:string}[]>([]);
 async function perform(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await action()}catch(e){setError(e instanceof Error?e.message:'Could not complete action')}finally{setBusy(false)}}
 return <section><h3>Authenticator protection</h3><p>Add a time-based authenticator and keep recovery codes in a private place. Never share the setup key or codes.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 {!setup&&<form className="admin-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void perform(async()=>setSetup(await requestJson('/api/auth/two-factor/enable','POST',{password:f.get('password')})))}}><label htmlFor="mfa-password">Current password</label><PasswordInput id="mfa-password" name="password" required autoComplete="current-password"/><Button disabled={busy}>Set up authenticator</Button></form>}
 {setup&&<><p>Open this setup link in your authenticator, or copy it into a trusted authenticator that accepts setup URIs.</p><LocalQr value={setup.totpURI} label="Private authenticator setup QR"/><a href={setup.totpURI}>Add SurakshaAr to authenticator</a><Input aria-label="Private authenticator setup URI" value={setup.totpURI} readOnly onFocus={e=>e.target.select()}/><p>Save these one-use recovery codes before continuing:</p><pre className="break-all">{setup.backupCodes.join('\n')}</pre><form className="admin-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void perform(async()=>{await requestJson('/api/auth/two-factor/verify-totp','POST',{code:f.get('code')});setSetup(null);setMessage('Authenticator enabled. Future sign-ins require your second factor. Keep your recovery codes private.')})}}><label>Code from authenticator<Input name="code" autoComplete="one-time-code" inputMode="numeric" required pattern="[0-9]{6}"/></label><Button disabled={busy}>Verify and enable</Button></form></>}
 <h3>Verify account email</h3><Button disabled={busy} variant="outline" onClick={()=>void perform(async()=>{const s=await requestJson<{user:{email:string}}>('/api/auth/get-session');await requestJson('/api/auth/send-verification-email','POST',{email:s.user.email,callbackURL:'/learn'});setMessage('Verification requested. Local mode delivers it to the development inbox on the host.');})}>Request verification link</Button>
 <h3>Signed-in devices</h3><Button variant="outline" disabled={busy} onClick={()=>void perform(async()=>setSessions(await requestJson('/api/auth/list-sessions')))}>Show sessions</Button>{sessions.map(s=><p key={s.token}>{s.userAgent||'Device not reported'} · {new Date(s.createdAt).toLocaleString()} <Button disabled={busy} variant="outline" onClick={()=>void perform(async()=>{await requestJson('/api/auth/revoke-session','POST',{token:s.token});setSessions(list=>list.filter(x=>x.token!==s.token));setMessage('Session revoked.')})}>Revoke</Button></p>)}</section>
}
export function Reauthenticate({email,owner}:{email:string;owner:string}){
 const [busy,setBusy]=useState(false),[challenge,setChallenge]=useState(false),[message,setMessage]=useState('');
 return <details className="review-card"><summary>Confirm sign-in for a sensitive decision</summary><p>Your review form stays on this page.</p><form className="admin-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setMessage('');const f=new FormData(e.currentTarget);try{const r=await requestJson<{twoFactorRedirect?:boolean}>(challenge?'/api/auth/two-factor/verify-totp':'/api/auth/sign-in/email','POST',challenge?{code:f.get('code')}:{email,password:f.get('password'),rememberMe:false});if(r.twoFactorRedirect){setChallenge(true)}else{await requestJson('/api/admin/session','POST',{owner});setChallenge(false);setMessage('Sign-in confirmed. Continue your review.')}}catch(e){setMessage(e instanceof Error?e.message:'Sign-in failed')}finally{setBusy(false)}}}>{challenge?<label>Authenticator code<Input name="code" autoComplete="one-time-code" required/></label>:<><label htmlFor="review-password">Password for {email}</label><PasswordInput id="review-password" name="password" autoComplete="current-password" required/></>}<Button disabled={busy}>Confirm sign-in</Button><p role="status">{message}</p></form></details>
}
