package com.narvyn.suraksha

/** Authored teaching cases; never camera classification or a change to the saved AR scenario. */
internal object FireResponseLearning {
    data class Choice(val label:RoomLearning.Text,val feedback:RoomLearning.Text,val suitable:Boolean)
    data class Case(val id:String,val title:RoomLearning.Text,val situation:RoomLearning.Text,val choices:List<Choice>)
    private fun text(en:String,hi:String)=RoomLearning.Text(en,hi)
    private fun option(en:String,hi:String,why:String,whyHi:String,ok:Boolean=false)=Choice(text(en,hi),text(why,whyHi),ok)
    val cases=listOf(
        Case("solids",text("Wood & paper · Class A","लकड़ी और कागज़ · वर्ग A"),text("Known ordinary solids are burning. No liquid, electrical or chemical hazard is present. Which equipment label should an authorised responder look for?","ज्ञात सामान्य ठोस पदार्थ जल रहे हैं। तरल, बिजली या रसायन का खतरा नहीं है। अधिकृत व्यक्ति कौन-सा उपकरण लेबल जाँचे?"),listOf(
            option("A-rated extinguisher","A रेटिंग का अग्निशामक","Check the marked A rating and the site's procedure. Water can suit ordinary solids only when incompatible hazards are excluded.","A रेटिंग और स्थल प्रक्रिया जाँचें। पानी सामान्य ठोस आग के लिए तभी उपयुक्त हो सकता है जब असंगत खतरे न हों।",true),
            option("Any red cylinder","कोई भी लाल सिलेंडर","Colour does not establish suitability. Read the agent, rating and instructions.","रंग से उपयुक्तता तय नहीं होती। माध्यम, रेटिंग और निर्देश पढ़ें।"))),
        Case("liquid",text("Diesel spill · Class B","डीज़ल का फैलाव · वर्ग B"),text("This example contains burning diesel, not cooking oil. Choose a response principle.","इस उदाहरण में डीज़ल जल रहा है, खाना पकाने का तेल नहीं। प्रतिक्रिया का सिद्धांत चुनें।"),listOf(
            option("Throw a bucket of water","पानी की बाल्टी डालें","An ordinary water jet can spread burning liquid. Do not improvise with water.","साधारण पानी की धार जलते तरल को फैला सकती है। पानी से प्रयोग न करें।"),
            option("Match a B-rated unit to the fuel","ईंधन के लिए B रेटिंग जाँचें","Foam, CO₂ or dry chemical may be suitable when specifically rated and permitted for this fuel and setting. Confirm the label and site plan.","फोम, CO₂ या रासायनिक पाउडर तभी उपयुक्त हो सकता है जब इस ईंधन और स्थान के लिए रेटिंग तथा अनुमति हो। लेबल और स्थल योजना जाँचें।",true))),
        Case("electrical",text("Energised electrical panel","चालू विद्युत पैनल"),text("The panel's power isolation is unconfirmed. Treat it as energised. Electrical involvement is an additional hazard; India's Class C refers to gases.","पैनल की बिजली अलग होने की पुष्टि नहीं है। इसे चालू मानें। बिजली एक अतिरिक्त खतरा है; भारत में वर्ग C गैसों के लिए है।"),listOf(
            option("Use ordinary water or foam","साधारण पानी या फोम लें","Do not apply ordinary water or foam to energised equipment. Do not touch the panel to investigate.","चालू उपकरण पर साधारण पानी या फोम न डालें। जाँच के लिए पैनल न छुएँ।"),
            option("Withdraw; only use explicitly suitable equipment if authorised","वापस हटें; अधिकृत हों तभी स्पष्ट उपयुक्त उपकरण लें","Only a trained, authorised response with an extinguisher tested for electrical involvement is considered. Specialist water-mist approval is not permission to use ordinary water.","केवल प्रशिक्षित, अधिकृत व्यक्ति बिजली के लिए परीक्षित अग्निशामक पर विचार करे। विशेष वॉटर-मिस्ट की अनुमति साधारण पानी की अनुमति नहीं है।",true))),
        Case("gas",text("Leaking fuel gas · Class C","रिसती ईंधन गैस · वर्ग C"),text("A gas leak and possible explosion risk are announced. Your role is a new worker outside the response team.","गैस रिसाव और संभावित विस्फोट बताया गया है। आपकी भूमिका प्रतिक्रिया दल से बाहर नए कर्मचारी की है।"),listOf(
            option("Alarm, withdraw and report","अलार्म, निकासी और सूचना","Correct for this role. Leave fuel isolation and firefighting to the designated team following its procedure.","इस भूमिका के लिए सही। ईंधन अलग करना और आग पर कार्रवाई निर्धारित दल की प्रक्रिया के अनुसार हो।",true),
            option("Try to put out the leaking flame","रिसती गैस की लौ बुझाने जाएँ","Do not approach or improvise. Extinguishing a flame does not stop the leak and can leave unburned gas accumulating.","पास न जाएँ और प्रयोग न करें। लौ बुझने से रिसाव नहीं रुकता; बिना जली गैस जमा हो सकती है।"))),
        Case("metal",text("Reactive metal · Class D","प्रतिक्रियाशील धातु · वर्ग D"),text("The identified material is burning magnesium swarf. Your standard ABC unit is nearby.","पहचाना पदार्थ जलती मैग्नीशियम की कतरन है। पास सामान्य ABC उपकरण है।"),listOf(
            option("Use the standard ABC unit","सामान्य ABC उपकरण लें","ABC does not mean every material. Do not substitute ordinary powder, water or CO₂ for a metal-specific response.","ABC का अर्थ हर पदार्थ नहीं है। धातु की विशेष प्रतिक्रिया की जगह सामान्य पाउडर, पानी या CO₂ न लें।"),
            option("Withdraw; require metal-specific powder and a trained team","हटें; धातु-विशेष पाउडर और प्रशिक्षित दल चाहिए","The powder must be suitable for the specific metal. A nearby sand bucket does not establish that suitability.","पाउडर उस विशिष्ट धातु के लिए उपयुक्त होना चाहिए। पास रेत की बाल्टी होने से उपयुक्तता सिद्ध नहीं होती।",true))),
        Case("cooking",text("Hot cooking oil · Class F","गर्म खाना पकाने का तेल · वर्ग F"),text("A canteen fryer contains burning hot oil. What must be ruled out?","कैंटीन के फ्रायर में गर्म तेल जल रहा है। कौन-सा विकल्प रोकना जरूरी है?"),listOf(
            option("Water is a cooling shortcut","पानी से जल्दी ठंडा करें","Never pour water on burning cooking oil: violent splashing can spread the fire and cause burns.","जलते खाना पकाने के तेल में पानी कभी न डालें: तेज़ छींटों से आग फैल सकती है और व्यक्ति जल सकता है।"),
            option("No water; follow the F-rated response plan","पानी नहीं; F रेटिंग वाली योजना मानें","A marked F-rated wet-chemical unit is the appropriate category for this example, used by the trained designated responder. Do not move the fryer.","इस उदाहरण की श्रेणी F रेटिंग वाला वेट-केमिकल उपकरण है, जिसे निर्धारित प्रशिक्षित व्यक्ति उपयोग करे। फ्रायर न हिलाएँ।",true))),
        Case("sand",text("Is sand always suitable?","क्या रेत हमेशा उपयुक्त है?"),text("A sand bucket is available, but the burning material and the site's approved response are unknown.","रेत की बाल्टी उपलब्ध है, पर जलता पदार्थ और स्थल की स्वीकृत प्रतिक्रिया अज्ञात हैं।"),listOf(
            option("Use sand on every small fire","हर छोटी आग पर रेत डालें","Sand is not a universal extinguisher. Do not assume unknown or damp sand is compatible with chemicals or metals.","रेत सार्वभौमिक अग्निशामक नहीं है। अज्ञात या नम रेत को रसायन या धातु के लिए उपयुक्त न मानें।"),
            option("Withdraw; first require a known material and approved method","हटें; ज्ञात पदार्थ और स्वीकृत विधि जरूरी है","Some site procedures specify dry sand for a particular risk. That does not authorise its use here; trained staff must follow the exact procedure.","कुछ स्थल प्रक्रियाएँ किसी विशेष खतरे के लिए सूखी रेत बताती हैं। इससे यहाँ उपयोग की अनुमति नहीं मिलती; प्रशिक्षित दल सटीक प्रक्रिया माने।",true)))
    )
    fun pages(hi:Boolean):List<RoomLearningDialog.Page> {
        fun t(en:String,h:String)=if(hi)h else en
        val pages=mutableListOf(RoomLearningDialog.Page(t("Identify before choosing","चुनने से पहले पहचानें"),t(
            "Ask: what is burning, is power or fuel still connected, and is escape clear? Use known materials and site information. Do not judge the fire from flame colour. Unknown material, spreading fire, smoke blocking escape or explosion risk means alarm, withdraw and report.",
            "पूछें: क्या जल रहा है, बिजली या ईंधन जुड़ा है, और निकास खुला है? ज्ञात पदार्थ और स्थल जानकारी लें। लौ के रंग से निर्णय न लें। अज्ञात पदार्थ, फैलती आग, निकास रोकता धुआँ या विस्फोट का खतरा हो तो अलार्म, निकासी और सूचना दें।"),t("Authored examples only. This guide neither detects a real fire nor changes the current AR scenario.","केवल लिखे गए उदाहरण। यह न वास्तविक आग पहचानता है, न मौजूदा AR दृश्य बदलता है।")))
        pages.addAll(cases.map{c->RoomLearningDialog.Page(c.title.local(hi),c.situation.local(hi),t("Choose, read the reason, then compare with the next example.","चुनें, कारण पढ़ें, फिर अगले उदाहरण से तुलना करें।"),Palette.soft,c.choices.map{RoomLearningDialog.Choice(it.label.local(hi),it.feedback.local(hi),it.suitable)})})
        pages.add(RoomLearningDialog.Page(t("Check the actual unit","वास्तविक उपकरण जाँचें"),t("Before the simulated pin action: read the agent, rating and operating label. Check the service status, damage, pin and seal, hose/nozzle and the pressure indicator if fitted. Do not test-discharge to check readiness. A CO₂ unit may have no gauge.","काल्पनिक पिन क्रिया से पहले: माध्यम, रेटिंग और संचालन लेबल पढ़ें। सेवा स्थिति, नुकसान, पिन-सील, होज़/नोज़ल और लगा हो तो दबाव सूचक जाँचें। तैयारी जाँचने के लिए डिस्चार्ज न करें। CO₂ उपकरण में गेज न भी हो सकता है।"),t("A label you cannot confirm is a reason to stop and report.","जिस लेबल की पुष्टि न हो, उस पर रुकें और सूचना दें।"),Palette.amberBg))
        pages.add(RoomLearningDialog.Page(t("P · Pull / A · Aim","P · पिन / A · निशाना"),t("In this approved-unit rehearsal, prepare the pin only after suitability and escape are confirmed. Drag the ring outward. Aim at the highlighted base, not the tops of the flames. Use the actual unit's instructions and effective range; the AR spacing is not a firefighting distance.","स्वीकृत उपकरण के अभ्यास में उपयुक्तता और निकास की पुष्टि के बाद पिन तैयार करें। छल्ला बाहर खींचें। लौ के ऊपरी भाग के बजाय चिह्नित आधार पर निशाना रखें। वास्तविक उपकरण के निर्देश और प्रभावी दूरी मानें; AR अंतर आग बुझाने की दूरी नहीं है।")))
        pages.add(RoomLearningDialog.Page(t("S · Squeeze / S · Sweep","S · दबाएँ / S · स्वीप"),t("Hold the virtual discharge control and turn the phone smoothly across the base. Cover the middle too. Stop when conditions worsen or the unit empties; keep your escape available. Do not advance into the virtual hazard. Do not grasp an uninsulated CO₂ discharge horn.","काल्पनिक डिस्चार्ज दबाकर फ़ोन धीरे आधार के आर-पार घुमाएँ। बीच का भाग भी शामिल करें। स्थिति बिगड़े या उपकरण खाली हो तो रुकें; निकास खुला रखें। काल्पनिक खतरे की ओर न बढ़ें। बिना इन्सुलेशन वाला CO₂ डिस्चार्ज हॉर्न न पकड़ें।")))
        pages.add(RoomLearningDialog.Page(t("Finish with accountability","अंत में उपस्थिति और सूचना"),t("Withdraw, reach the designated assembly point and report missing people and used equipment. Do not re-enter or return the used unit to service yourself. Explain which condition would make you stop sooner next time.","निकासी करें, निर्धारित एकत्र स्थल पहुँचें और लापता लोगों तथा उपयोग किए उपकरण की सूचना दें। दोबारा प्रवेश या उपकरण स्वयं सेवा में वापस न करें। समझाएँ कि अगली बार किस स्थिति पर जल्दी रुकेंगे।"),t("Practice feedback only; these choices do not issue or upgrade a certificate.","केवल अभ्यास प्रतिक्रिया; इन विकल्पों से प्रमाणपत्र बनता या उन्नत नहीं होता।")))
        return pages
    }
}
