package com.narvyn.suraksha

/** Generated from content/scenario-additions-v2.json by scripts/generate-scenarios.py. */
object ScenarioAdditions {
 val modules = mapOf(
  "fire" to listOf(
   ProcedureCatalog.Step("fire-service","Inspect the virtual inspection label: service status is unconfirmed.","काल्पनिक जाँच लेबल में सेवा स्थिति अपुष्ट है।","An unconfirmed unit is not accepted in this scenario. The next scene supplies a confirmed replacement.","अपुष्ट उपकरण इस दृश्य में स्वीकार्य नहीं। अगले दृश्य में जाँचा विकल्प मिलेगा।",listOf(ProcedureCatalog.Action("fire-service","Set this unit aside and request a confirmed replacement","यह उपकरण अलग रखकर जाँचा विकल्प माँगें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("fire-service-unsafe","Treat the label as optional","लेबल को गैरज़रूरी मानें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("fire-hose","The replacement has a visibly damaged hose. Inspect before selecting it.","बदले उपकरण की नली खराब है। चुनने से पहले देखें।","Inspect condition as well as suitability. This rejection changes the scenario to a further replacement.","उपयुक्तता के साथ स्थिति भी जाँचें। अस्वीकार करने पर दृश्य में दूसरा विकल्प आएगा।",listOf(ProcedureCatalog.Action("fire-hose","Reject the damaged unit","खराब उपकरण अस्वीकार करें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("fire-hose-unsafe","Cover the damage and continue","खराब हिस्सा ढककर जारी रखें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("fire-gauge","A new unit has a model-specific status indicator.","नए उपकरण पर मॉडल-विशिष्ट स्थिति संकेतक है।","Illustrations are not manufacturer instructions. Only the scenario label confirms this unit.","चित्र निर्माता के निर्देश नहीं हैं। इस उपकरण की पुष्टि दृश्य का लेबल करता है।",listOf(ProcedureCatalog.Action("fire-gauge","Compare the indicator with its approved label","संकेतक को स्वीकृत लेबल से मिलाएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("fire-gauge-unsafe","Assume every indicator uses the same limits","सभी संकेतकों की सीमा एक मानें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("fire-handover","At assembly, the responsible person asks what happened.","एकत्र स्थल पर प्रभारी घटना पूछता है।","A clear handover separates observed information from assumptions.","स्पष्ट सूचना में देखी जानकारी और अनुमान अलग रखें।",listOf(ProcedureCatalog.Action("fire-handover","Report location, changed conditions and missing colleague","जगह, बदले हालात और लापता साथी बताएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("fire-handover-unsafe","Report that the site is safe without evidence","बिना प्रमाण स्थल सुरक्षित बताएँ",false,floatArrayOf(0.28f,0.28f,0.12f))))
  ),
  "gas" to listOf(
   ProcedureCatalog.Step("gas-instrument","The SIM instrument shows a low-battery warning.","SIM उपकरण कम बैटरी दिखाता है।","The phone is never a gas detector. The instrument status is a scenario prompt.","फ़ोन गैस जाँच उपकरण नहीं है। उपकरण की स्थिति दृश्य का संकेत है।",listOf(ProcedureCatalog.Action("gas-instrument","Flag the instrument and request an authorised check","उपकरण चिन्हित करके अधिकृत जाँच माँगें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("gas-instrument-unsafe","Treat SIM as an atmospheric reading","SIM को वातावरण की रीडिंग मानें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("gas-record","The instrument check record is missing.","उपकरण की जाँच का रिकॉर्ड नहीं है।","Missing verification is not a passed check. Do not invent measurements.","अपुष्ट जाँच पास नहीं है। रीडिंग अपने से न बनाएँ।",listOf(ProcedureCatalog.Action("gas-record","Hold the task and refer to the responsible person","काम रोककर ज़िम्मेदार व्यक्ति को बताएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("gas-record-unsafe","Invent a successful check","सफल जाँच अपने से दर्ज करें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("gas-contact-loss","Radio contact is lost during the outside-role rehearsal.","बाहरी भूमिका के अभ्यास में रेडियो संपर्क टूट गया।","Conditions can change after a checklist is completed. A previous reply is not continuous communication.","सूची पूरी होने के बाद हालात बदल सकते हैं। पिछला उत्तर लगातार संपर्क नहीं है।",listOf(ProcedureCatalog.Action("gas-contact-loss","Keep entry closed and report the failed contact","प्रवेश बंद रखें और संपर्क विफलता बताएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("gas-contact-loss-unsafe","Continue because earlier contact worked","पहले संपर्क था इसलिए जारी रखें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("gas-handover","A replacement attendant arrives.","बदला परिचर आता है।","Handover preserves the unresolved risk; it does not grant permission to enter.","जानकारी देने से अधूरा खतरा स्पष्ट रहता है; प्रवेश अनुमति नहीं मिलती।",listOf(ProcedureCatalog.Action("gas-handover","Hand over the unresolved controls and closed-entry status","अधूरे नियंत्रण और बंद प्रवेश की स्थिति बताएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("gas-handover-unsafe","Leave without a handover","बिना जानकारी दिए चले जाएँ",false,floatArrayOf(0.28f,0.28f,0.12f))))
  ),
  "machinery" to listOf(
   ProcedureCatalog.Step("mach-role","A conveyor has stopped. A colleague asks you to clear a jam.","कन्वेयर रुका है। साथी जाम हटाने को कहता है।","A stopped machine can still contain hazardous energy. This exercise grants no authority.","रुकी मशीन में भी खतरनाक ऊर्जा हो सकती है। अभ्यास अधिकार नहीं देता।",listOf(ProcedureCatalog.Action("mach-role","Confirm the authorised role and approved procedure","अधिकृत भूमिका और स्वीकृत प्रक्रिया जाँचें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-role-unsafe","Start work because the conveyor is stopped","कन्वेयर रुका है इसलिए काम शुरू करें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("mach-sources","Inspect the illustrated electrical drive and raised load.","दिखाए विद्युत ड्राइव और उठे भार को देखें।","Consider all energy sources identified in the equipment-specific procedure.","उपकरण-विशिष्ट प्रक्रिया की सभी ऊर्जा पहचानें।",listOf(ProcedureCatalog.Action("mach-sources","Identify both electrical and stored mechanical energy","विद्युत और जमा यांत्रिक ऊर्जा दोनों पहचानें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-sources-unsafe","Identify only the start button","केवल स्टार्ट बटन पहचानें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("mach-notify","People nearby may operate the machine.","पास के लोग मशीन चला सकते हैं।","Communication is part of the planned isolation process.","संचार नियोजित अलगाव का हिस्सा है।",listOf(ProcedureCatalog.Action("mach-notify","Notify affected people through the agreed process","तय प्रक्रिया से संबंधित लोगों को बताएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-notify-unsafe","Rely on them noticing the work","उनके खुद देखने पर भरोसा करें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("mach-isolate","The scene offers a stop button and an identified isolating device.","दृश्य में स्टॉप बटन और पहचाना अलगाव उपकरण है।","Normal controls are not automatically energy-isolating devices.","सामान्य नियंत्रण अपने आप ऊर्जा अलगाव उपकरण नहीं होते।",listOf(ProcedureCatalog.Action("mach-isolate","Identify the procedure-defined isolation point","प्रक्रिया का अलगाव बिंदु पहचानें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-isolate-unsafe","Treat the stop button as isolation","स्टॉप बटन को अलगाव मानें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("mach-lock","The authorised worker has a personal lock and identification tag.","अधिकृत कर्मचारी के पास निजी लॉक और पहचान टैग है।","The model rehearses responsibility and identification, not a live locking procedure.","मॉडल ज़िम्मेदारी और पहचान का अभ्यास है, वास्तविक लॉक प्रक्रिया नहीं।",listOf(ProcedureCatalog.Action("mach-lock","Match the lock and tag to that authorised worker","लॉक और टैग को उसी अधिकृत व्यक्ति से मिलाएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-lock-unsafe","Borrow another person’s lock identity","दूसरे व्यक्ति की लॉक पहचान लें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("mach-stored","The raised load remains an unresolved stored-energy hazard.","उठा भार अब भी जमा ऊर्जा का अधूरा खतरा है।","Stored energy requires the specific approved controls and verification.","जमा ऊर्जा के लिए विशिष्ट स्वीकृत नियंत्रण और पुष्टि चाहिए।",listOf(ProcedureCatalog.Action("mach-stored","Request the procedure-defined stored-energy controls","प्रक्रिया के जमा ऊर्जा नियंत्रण माँगें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-stored-unsafe","Assume a lock removes every stored hazard","मान लें लॉक हर जमा खतरा हटा देता है",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("mach-verify","A colleague claims isolation is complete without a verification record.","साथी बिना पुष्टि रिकॉर्ड अलगाव पूरा बताता है।","Verification is separate from applying a control.","पुष्टि नियंत्रण लगाने से अलग है।",listOf(ProcedureCatalog.Action("mach-verify","Hold work for authorised verification","अधिकृत पुष्टि तक काम रोकें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-verify-unsafe","Start because the colleague is confident","साथी को भरोसा है इसलिए शुरू करें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("mach-shift","A shift change occurs while the task remains open.","काम जारी है और शिफ्ट बदलती है।","Responsibility must remain clear through changes of personnel.","कर्मचारियों के बदलाव में ज़िम्मेदारी स्पष्ट रहनी चाहिए।",listOf(ProcedureCatalog.Action("mach-shift","Use the approved transfer and handover process","स्वीकृत बदलाव और जानकारी प्रक्रिया अपनाएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-shift-unsafe","Remove another worker’s lock to save time","समय बचाने के लिए दूसरे का लॉक हटाएँ",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("mach-restart","The simulated maintenance is finished; a guard is still missing.","काल्पनिक रखरखाव पूरा है; गार्ड नहीं लगा।","An incomplete restoration check is a reason to hold the restart.","अधूरी बहाली जाँच रीस्टार्ट रोकने का कारण है।",listOf(ProcedureCatalog.Action("mach-restart","Keep restart on hold and report the missing guard","रीस्टार्ट रोकें और गायब गार्ड बताएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-restart-unsafe","Restart to test before replacing the guard","गार्ड लगाने से पहले परीक्षण चलाएँ",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("mach-report","Complete the handover with remaining restrictions.","बची सीमाओं के साथ जानकारी पूरी करें।","Only the actual authorised site process determines release for work.","काम की अनुमति वास्तविक अधिकृत कार्यस्थल प्रक्रिया तय करती है।",listOf(ProcedureCatalog.Action("mach-report","Record status and responsible person","स्थिति और ज़िम्मेदार व्यक्ति दर्ज करें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("mach-report-unsafe","Claim unrestricted permission to operate","बिना सीमा संचालन अनुमति बताएं",false,floatArrayOf(0.28f,0.28f,0.12f))))
  ),
  "ppe" to listOf(
   ProcedureCatalog.Step("ppe-hazard","The scenario describes flying particles and a designated outside role.","दृश्य में उड़ते कण और तय बाहरी भूमिका है।","PPE selection starts with assessed hazards and the assigned task.","पीपीई चयन जाँचे खतरे और तय काम से शुरू होता है।",listOf(ProcedureCatalog.Action("ppe-hazard","Review the assessed hazard and role first","पहले जाँचा खतरा और भूमिका देखें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("ppe-hazard-unsafe","Pick equipment by colour","रंग से उपकरण चुनें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("ppe-label","Two similar items have different approved uses.","दो समान चीज़ों का स्वीकृत उपयोग अलग है।","Shape alone does not establish suitability.","केवल आकार उपयुक्तता नहीं बताता।",listOf(ProcedureCatalog.Action("ppe-label","Inspect labels against the specified kit","लेबल को निर्धारित किट से मिलाएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("ppe-label-unsafe","Assume similar shapes mean equal protection","समान आकार को समान सुरक्षा मानें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("ppe-crack","The helmet illustration shows a crack in the shell.","हेलमेट के चित्र में खोल की दरार है।","Damaged equipment must be handled under the approved replacement process.","खराब उपकरण स्वीकृत बदलाव प्रक्रिया से संभालें।",listOf(ProcedureCatalog.Action("ppe-crack","Mark defective and replace","खराब चिन्हित करके बदलें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("ppe-crack-unsafe","Cover the crack with tape","दरार टेप से ढकें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("ppe-eye","The eye protection is damaged and blocks the view.","आँख सुरक्षा खराब है और देखने में बाधा है।","Resolve the equipment problem before resuming the task.","काम फिर शुरू करने से पहले उपकरण समस्या हल करें।",listOf(ProcedureCatalog.Action("ppe-eye","Choose an approved undamaged replacement","स्वीकृत ठीक विकल्प चुनें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("ppe-eye-unsafe","Remove protection while continuing the task","सुरक्षा हटाकर काम जारी रखें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("ppe-glove","The supplied glove has a visible tear.","दिए दस्ताने में दिखाई देने वाला फटाव है।","Inspection should lead to a recorded replacement action.","निरीक्षण के बाद बदलाव की क्रिया दर्ज होनी चाहिए।",listOf(ProcedureCatalog.Action("ppe-glove","Reject the torn glove","फटा दस्ताना अस्वीकार करें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("ppe-glove-unsafe","Hide the tear under the cuff","फटाव कफ के नीचे छिपाएँ",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("ppe-compatible","The selected items must work together.","चुनी चीज़ें साथ सही काम करें।","A phone model cannot prove fit or replace required physical checks.","फ़ोन मॉडल फिट साबित नहीं कर सकता या वास्तविक जाँच की जगह नहीं लेता।",listOf(ProcedureCatalog.Action("ppe-compatible","Request the required compatibility and fit checks","ज़रूरी अनुकूलता और फिट जाँच लें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("ppe-compatible-unsafe","Accept the virtual model as proof of physical fit","काल्पनिक मॉडल को असली फिट का प्रमाण मानें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("ppe-change","The task changes to an unassessed atmosphere.","काम अब बिना जाँचे वातावरण में बदल गया।","Changing hazards can invalidate the previous equipment choice.","बदलते खतरे पिछला उपकरण चयन अनुपयुक्त कर सकते हैं।",listOf(ProcedureCatalog.Action("ppe-change","Stop and request reassessment of the controls","रुकें और नियंत्रण का फिर आकलन माँगें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("ppe-change-unsafe","Assume the same kit protects against everything","उसी किट को हर खतरे की सुरक्षा मानें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("ppe-store","The practice ends with equipment inspection and reporting.","अभ्यास उपकरण निरीक्षण और सूचना पर समाप्त होता है।","Prevent another worker from unknowingly receiving defective equipment.","दूसरे कर्मचारी को अनजाने खराब उपकरण मिलने से रोकें।",listOf(ProcedureCatalog.Action("ppe-store","Separate defective items and record the issue","खराब चीज़ें अलग करें और समस्या दर्ज करें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("ppe-store-unsafe","Return damaged items to shared stock","खराब चीज़ें साझा भंडार में रखें",false,floatArrayOf(0.28f,0.28f,0.12f))))
  ),
  "emergency" to listOf(
   ProcedureCatalog.Step("em-scene","A simulated incident is ahead; scene safety is unknown.","आगे काल्पनिक घटना है; स्थल सुरक्षा अज्ञात है।","Unplanned entry can create another casualty.","बिना योजना प्रवेश दूसरा घायल व्यक्ति बना सकता है।",listOf(ProcedureCatalog.Action("em-scene","Observe from the designated safe position","तय सुरक्षित जगह से देखें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("em-scene-unsafe","Rush into the scene","जल्दी में घटनास्थल में जाएँ",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("em-alert","The emergency contact needs an initial report.","आपात संपर्क को शुरुआती सूचना चाहिए।","Report observations clearly and identify uncertainty.","देखी जानकारी स्पष्ट दें और अनिश्चितता बताएं।",listOf(ProcedureCatalog.Action("em-alert","Give location, incident type and observed hazards","जगह, घटना प्रकार और देखे खतरे बताएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("em-alert-unsafe","Give an unverified all-clear","बिना जाँच सब सुरक्षित बताएँ",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("em-route","The first marked route is now obstructed.","पहला चिह्नित मार्ग अब बंद है।","The scenario changes the route. Virtual signs never identify actual exits.","दृश्य मार्ग बदलता है। काल्पनिक संकेत असली निकास नहीं बताते।",listOf(ProcedureCatalog.Action("em-route","Select the scenario’s designated alternate route","दृश्य का तय वैकल्पिक मार्ग चुनें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("em-route-unsafe","Continue into the obstruction","बाधा में आगे बढ़ें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("em-support","A colleague needs assistance beyond your training.","साथी को आपके प्रशिक्षण से अधिक सहायता चाहिए।","Follow the site plan and your actual training; this exercise teaches reporting.","कार्यस्थल योजना और अपने वास्तविक प्रशिक्षण का पालन करें; यह सूचना का अभ्यास है।",listOf(ProcedureCatalog.Action("em-support","Report their location and request trained assistance","उनकी जगह बताकर प्रशिक्षित सहायता माँगें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("em-support-unsafe","Attempt an unplanned rescue","बिना योजना बचाव करें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("em-assembly","The group reaches the simulated assembly point.","दल काल्पनिक एकत्र स्थल पहुँचता है।","Accountability depends on people reporting their status.","उपस्थिति लोगों की स्थिति सूचना पर निर्भर है।",listOf(ProcedureCatalog.Action("em-assembly","Join the accountability check","उपस्थिति जाँच में शामिल हों",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("em-assembly-unsafe","Leave without reporting","बिना बताए चले जाएँ",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("em-missing","The roster lists six people; only five are accounted for.","सूची में छह लोग हैं; पाँच की पुष्टि हुई।","A discrepancy must be reported, not explained away by a guess.","अंतर की सूचना दें, अनुमान से उसे पूरा न मानें।",listOf(ProcedureCatalog.Action("em-missing","Report one unaccounted person to the coordinator","समन्वयक को एक अपुष्ट व्यक्ति बताएँ",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("em-missing-unsafe","Assume the sixth person went home","छठा घर गया होगा मान लें",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("em-rumour","Someone says it is safe to return without an authorised message.","कोई अधिकृत संदेश बिना लौटना सुरक्षित बताता है।","An informal claim is not an authorised all-clear.","अनौपचारिक दावा अधिकृत अनुमति नहीं है।",listOf(ProcedureCatalog.Action("em-rumour","Wait for the designated authority’s instruction","तय अधिकारी के निर्देश की प्रतीक्षा करें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("em-rumour-unsafe","Return based on the rumour","अफवाह पर वापस जाएँ",false,floatArrayOf(0.28f,0.28f,0.12f)))),
   ProcedureCatalog.Step("em-log","The coordinator asks for a factual incident handover.","समन्वयक घटना की तथ्यात्मक जानकारी माँगता है।","An honest handover supports the next decision.","सही जानकारी अगले निर्णय में मदद करती है।",listOf(ProcedureCatalog.Action("em-log","Record observations, actions and unresolved issues","देखी बातें, क्रियाएँ और अधूरी समस्याएँ दर्ज करें",true,floatArrayOf(-0.22f,0.28f,0.12f)),ProcedureCatalog.Action("em-log-unsafe","Invent missing details to finish the form","फ़ॉर्म पूरा करने को जानकारी बनाएँ",false,floatArrayOf(0.28f,0.28f,0.12f))))
  )
 )
}
